"use client";

import { useMemo } from "react";
import Link from "next/link";
import { ArrowRight, Clock, FileText, RefreshCw, TrendingUp, Users } from "lucide-react";
import { api, type Report } from "@/lib/api";
import { usePolling, useNow } from "@/lib/hooks";
import { fmtDate, fmtRelative, humanize, num, pct } from "@/lib/format";
import { Badge, Button, Card, CardHeader, EmptyState, ErrorState, PageHeader, Skeleton, StatCard } from "@/components/ui";
import { AgentActions } from "@/components/agents/AgentActions";

function rate(v: unknown): number {
  const n = Number(v) || 0;
  return n <= 1 ? n * 100 : n;
}

export default function ReportsPage() {
  const { data, error, loading, refreshing, reload } = usePolling(() => api.reports(), 30_000);
  const now = useNow(30_000);

  const reports = useMemo(() => [...(data ?? [])].sort((a, b) => new Date(b.generated_at || b.end_date).getTime() - new Date(a.generated_at || a.end_date).getTime()), [data]);
  const latest = reports[0];

  const trend = useMemo(() => {
    const xs = [...reports].reverse().slice(-8);
    return {
      coverage: xs.map((r) => rate(r.coverage_rate)),
      noShow: xs.map((r) => rate(r.no_show_rate)),
      hours: xs.map((r) => Number(r.total_hours) || 0),
      labels: xs.map((r) => fmtDate(r.end_date)),
    };
  }, [reports]);

  return (
    <>
      <PageHeader
        eyebrow="Reports"
        title="Coverage and impact"
        description="Generated by the Reporter agent from real shift and hour data. Stored in DynamoDB and S3."
        actions={
          <Button variant="secondary" icon={RefreshCw} loading={refreshing} onClick={() => void reload()}>
            Refresh
          </Button>
        }
      />

      {error && !data && <ErrorState message={error} onRetry={() => void reload()} />}

      <div className="grid gap-6 lg:grid-cols-3">
        <div className="space-y-6 lg:col-span-2">
          <div className="stagger grid grid-cols-2 gap-4 xl:grid-cols-4">
            <StatCard label="Latest coverage" value={latest ? pct(latest.coverage_rate) : "—"} icon={TrendingUp} tone="success" loading={loading} hint={latest ? `${fmtDate(latest.start_date)} – ${fmtDate(latest.end_date)}` : undefined} />
            <StatCard label="No-show rate" value={latest ? pct(latest.no_show_rate) : "—"} icon={Users} tone={latest && rate(latest.no_show_rate) > 15 ? "danger" : "warning"} loading={loading} />
            <StatCard label="Hours delivered" value={latest ? num(latest.total_hours, 1) : "—"} icon={Clock} tone="info" loading={loading} />
            <StatCard label="Reports on file" value={reports.length} icon={FileText} tone="neutral" loading={loading} />
          </div>

          {reports.length >= 2 && (
            <Card>
              <CardHeader icon={TrendingUp} title="Trend across reports" subtitle="Oldest to newest" />
              <div className="grid gap-6 sm:grid-cols-3">
                <Spark label="Coverage" values={trend.coverage} format={(v) => `${v.toFixed(0)}%`} tone="#059669" />
                <Spark label="No-show rate" values={trend.noShow} format={(v) => `${v.toFixed(0)}%`} tone="#e11d48" />
                <Spark label="Hours" values={trend.hours} format={(v) => v.toFixed(0)} tone="#0284c7" />
              </div>
            </Card>
          )}

          {loading ? (
            <div className="space-y-3">
              {[0, 1, 2].map((i) => (
                <Skeleton key={i} className="h-28 rounded-2xl" />
              ))}
            </div>
          ) : reports.length === 0 ? (
            <Card>
              <EmptyState icon={FileText} title="No reports yet" description="Ask the Reporter agent for the first weekly report. It takes about a minute." />
            </Card>
          ) : (
            <div className="stagger space-y-3">
              {reports.map((r) => (
                <ReportRow key={r.id} r={r} now={now} />
              ))}
            </div>
          )}
        </div>

        <div className="space-y-6">
          <Card>
            <CardHeader icon={FileText} title="Generate a report" subtitle="Covers the last 7 days plus the next 14 of scheduled shifts." />
            <AgentActions actions={["report"]} onDone={() => void reload()} />
          </Card>
          <Card className="bg-slate-900 text-white">
            <h3 className="text-sm font-semibold">What is in a report</h3>
            <ul className="mt-3 space-y-2 text-sm text-slate-300">
              <li>Shifts and unique volunteers in the period</li>
              <li>Coverage rate: confirmed seats over required seats</li>
              <li>No-show rate from check-in data</li>
              <li>Total volunteer hours delivered</li>
            </ul>
            <p className="mt-4 text-xs text-slate-400">Full JSON is also written to the reports bucket for funders and boards.</p>
          </Card>
        </div>
      </div>
    </>
  );
}

function ReportRow({ r, now }: { r: Report; now: number }) {
  const cov = rate(r.coverage_rate);
  const ns = rate(r.no_show_rate);
  return (
    <Link href={`/reports/${encodeURIComponent(r.id)}`} className="card card-hover group block p-5">
      <div className="flex flex-wrap items-center gap-3">
        <Badge tone={r.period === "monthly" ? "violet" : "info"}>{humanize(r.period)}</Badge>
        <h3 className="text-sm font-semibold text-slate-900">
          {fmtDate(r.start_date)} – {fmtDate(r.end_date)}
        </h3>
        <span className="ml-auto text-xs text-slate-400">Generated {fmtRelative(r.generated_at, now)}</span>
        <ArrowRight className="h-4 w-4 text-slate-300 transition group-hover:translate-x-0.5 group-hover:text-slate-500" />
      </div>
      <dl className="mt-4 grid grid-cols-2 gap-4 sm:grid-cols-5">
        <Metric label="Shifts" value={num(r.total_shifts)} />
        <Metric label="Volunteers" value={num(r.total_volunteers)} />
        <Metric label="Hours" value={num(r.total_hours, 1)} />
        <Metric label="Coverage" value={`${cov.toFixed(0)}%`} tone={cov >= 90 ? "text-brand-600" : cov >= 70 ? "text-amber-600" : "text-rose-600"} />
        <Metric label="No-shows" value={`${ns.toFixed(0)}%`} tone={ns <= 10 ? "text-brand-600" : ns <= 20 ? "text-amber-600" : "text-rose-600"} />
      </dl>
    </Link>
  );
}

function Metric({ label, value, tone }: { label: string; value: string; tone?: string }) {
  return (
    <div>
      <dt className="text-[11px] uppercase tracking-wide text-slate-400">{label}</dt>
      <dd className={`text-lg font-semibold tabular ${tone ?? "text-slate-900"}`}>{value}</dd>
    </div>
  );
}

function Spark({ label, values, format, tone }: { label: string; values: number[]; format: (v: number) => string; tone: string }) {
  const w = 220;
  const h = 56;
  const max = Math.max(1, ...values);
  const min = Math.min(0, ...values);
  const span = max - min || 1;
  const pts = values.map((v, i) => {
    const x = values.length === 1 ? w / 2 : (i / (values.length - 1)) * (w - 8) + 4;
    const y = h - 6 - ((v - min) / span) * (h - 12);
    return [x, y] as const;
  });
  const d = pts.map(([x, y], i) => `${i === 0 ? "M" : "L"}${x.toFixed(1)},${y.toFixed(1)}`).join(" ");
  const area = `${d} L${pts[pts.length - 1]![0].toFixed(1)},${h} L${pts[0]![0].toFixed(1)},${h} Z`;
  const last = values[values.length - 1] ?? 0;
  const first = values[0] ?? 0;
  const delta = last - first;
  return (
    <div>
      <div className="flex items-baseline justify-between">
        <p className="text-xs font-medium text-slate-500">{label}</p>
        <p className="text-sm font-semibold tabular text-slate-900">
          {format(last)}
          <span className={`ml-1.5 text-[11px] font-medium ${delta >= 0 ? "text-brand-600" : "text-rose-600"}`}>
            {delta >= 0 ? "▲" : "▼"} {format(Math.abs(delta))}
          </span>
        </p>
      </div>
      <svg viewBox={`0 0 ${w} ${h}`} className="mt-1 h-14 w-full" preserveAspectRatio="none" aria-hidden>
        <path d={area} fill={tone} opacity={0.08} />
        <path d={d} fill="none" stroke={tone} strokeWidth={2} strokeLinejoin="round" strokeLinecap="round" />
        {pts.map(([x, y], i) => (
          <circle key={i} cx={x} cy={y} r={i === pts.length - 1 ? 3 : 2} fill={tone} />
        ))}
      </svg>
    </div>
  );
}
